server {
	# -----------------------------
	# 1. Логи
	# -----------------------------
	access_log /home/web-studio/raskatov/logs/access-http.log;
	error_log /home/web-studio/raskatov/logs/error-http.log;

	# -----------------------------
	# 2. server_name / listen
	# -----------------------------
	listen 80;
	listen [::]:80;
	server_name raskatov.efiand.ru;

	return 301 https://raskatov.efiand.ru$request_uri;
}

server {
	# -----------------------------
	# 1. Логи
	# -----------------------------
	access_log /home/web-studio/raskatov/logs/access.log;
	error_log /home/web-studio/raskatov/logs/error.log;

	# -----------------------------
	# 2. Error pages
	# -----------------------------
	error_page 404 /__/404/index.html;
	error_page 500 502 503 504 /__/update/index.html;

	# -----------------------------
	# 3. SSL и server_name / listen
	# -----------------------------
	include /etc/letsencrypt/options-ssl-nginx.conf;
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	server_name raskatov.efiand.ru;
	ssl_certificate /etc/letsencrypt/live/raskatov.efiand.ru/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/raskatov.efiand.ru/privkey.pem;
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

	# -----------------------------
	# 4. Location blocks (по приоритету)
	# -----------------------------

	## 4.1 Internal static / error pages
	location ^~ /__ {
		internal;
		add_header Cache-Control "no-store";
		etag off;
		gzip off;
		root /home/web-studio/raskatov/current/app;
	}

	## 4.2 Public static assets (regex)
	location ~* \.(css|ico|js|pdf|png|svg|txt|webmanifest|webp|woff2|xml)$ {
		root /home/web-studio/raskatov/current/public;
		charset utf-8;
		expires 30d;
	}

	## 4.3 Static pages
	location / {
		root /home/web-studio/raskatov/current/public;
		charset utf-8;
		expires 30d;

		rewrite ^/(.*)/(index.html)?$ /$1 permanent;
		try_files $uri/index.html =404;
	}
}
